### ISSUE TITLE
Passing withFS:true throws an error

### ISSUE THREAD

**Issue by phil-isaacs** [MichaelZaporozhets/abstractconnect#9]
I've been trying to pass in the withFS flag in my method and I'm getting an error. If only seems to work if you don't pass anything at all or set it to false:

Works

`getSymbols({
       withFS:false
    })`

Works

`getSymbols({ })`

This will break for me

`getSymbols({
       withFS:true
    })`

```
abstractconnect: downloading data... ==

ReferenceError: withFS is not defined
    at getSketchFileWithFS (/Users/localuser/Sites/test/dist/main.js:180:7)
    at getSketchFile (/Users/localuser/Sites/test/dist/main.js:192:38)
    at process._tickCallback (internal/process/next_tick.js:68:7)
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be one of type string, Buffer, or URL. Received type undefined
    at Object.openSync (fs.js:435:3)
    at Object.readFileSync (fs.js:343:35)
    at Function.fromFile (/Users/localuser/Sites/test/dist/main.js:15089:56)
    at getSymbols (/Users/localuser/Sites/test/dist/main.js:214:92)
    at process._tickCallback (internal/process/next_tick.js:68:7)
getSymbols Error:  TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at getSymbols.then.Symbols (/Users/localuser/Sites/test/tokens.js:84:35)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by MichaelZaporozhets** [comment]
@phil-isaacs Good catch. I've resolved this and published version 1.2.1 that resolves this issue.
